import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Designer Sunglasses",
    description: "Premium UV-protected sunglasses with stylish frames. Perfect for both fashion and eye protection.",
    price: 2499,
    discount: 15,
    categoryId: "eyewear",
    categoryName: "Eyewear",
    stock: 45,
    images: [
      "https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    isNew: true,
    region: "india",
    createdAt: "2023-11-15T00:00:00Z",
    variants: {
      colors: [
        { name: "Matte Black", value: "#000000" },
        { name: "Tortoise", value: "#8B4513" },
        { name: "Silver", value: "#C0C0C0" },
      ],
    },
  },
  {
    id: "p2",
    name: "Leather Watch Band",
    description: "Genuine leather watch band compatible with all standard watches. Comfortable and durable.",
    price: 999,
    discount: 0,
    categoryId: "accessories",
    categoryName: "Accessories",
    stock: 120,
    images: [
      "https://images.pexels.com/photos/9978722/pexels-photo-9978722.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/1034063/pexels-photo-1034063.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    isBestseller: true,
    region: "global",
    createdAt: "2023-09-20T00:00:00Z",
    variants: {
      colors: [
        { name: "Brown", value: "#8B4513" },
        { name: "Black", value: "#000000" },
      ],
    },
  },
  {
    id: "p3",
    name: "Wireless Earbuds",
    description: "High-quality wireless earbuds with noise cancellation and long battery life. Perfect for music and calls.",
    price: 3499,
    discount: 10,
    categoryId: "electronics",
    categoryName: "Electronics",
    stock: 75,
    images: [
      "https://images.pexels.com/photos/3394665/pexels-photo-3394665.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/3780681/pexels-photo-3780681.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    isNew: true,
    isBestseller: true,
    region: "global",
    createdAt: "2024-01-05T00:00:00Z",
  },
  {
    id: "p4",
    name: "Minimalist Desk Lamp",
    description: "Modern, adjustable desk lamp with LED lighting and multiple brightness levels. Energy efficient design.",
    price: 1999,
    discount: 0,
    categoryId: "home-decor",
    categoryName: "Home Decor",
    stock: 60,
    images: [
      "https://images.pexels.com/photos/1112598/pexels-photo-1112598.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/6492402/pexels-photo-6492402.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    region: "india",
    createdAt: "2023-10-10T00:00:00Z",
    variants: {
      colors: [
        { name: "White", value: "#FFFFFF" },
        { name: "Black", value: "#000000" },
      ],
    },
  },
  {
    id: "p5",
    name: "Polarized Aviator Sunglasses",
    description: "Classic aviator style with polarized lenses for superior glare reduction. Lightweight metal frame.",
    price: 1899,
    discount: 5,
    categoryId: "eyewear",
    categoryName: "Eyewear",
    stock: 90,
    images: [
      "https://images.pexels.com/photos/46710/pexels-photo-46710.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    region: "usa",
    createdAt: "2023-11-25T00:00:00Z",
    variants: {
      colors: [
        { name: "Gold", value: "#FFD700" },
        { name: "Silver", value: "#C0C0C0" },
      ],
    },
  },
  {
    id: "p6",
    name: "Leather Wallet",
    description: "Handcrafted genuine leather wallet with multiple card slots and compartments. Slim design.",
    price: 1499,
    discount: 0,
    categoryId: "accessories",
    categoryName: "Accessories",
    stock: 150,
    images: [
      "https://images.pexels.com/photos/6690848/pexels-photo-6690848.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/6690850/pexels-photo-6690850.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    isBestseller: true,
    region: "global",
    createdAt: "2023-08-15T00:00:00Z",
    variants: {
      colors: [
        { name: "Brown", value: "#8B4513" },
        { name: "Black", value: "#000000" },
      ],
    },
  },
  {
    id: "p7",
    name: "Portable Bluetooth Speaker",
    description: "Compact, waterproof Bluetooth speaker with 360-degree sound. Up to 12 hours of battery life.",
    price: 2499,
    discount: 20,
    categoryId: "electronics",
    categoryName: "Electronics",
    stock: 85,
    images: [
      "https://images.pexels.com/photos/1279107/pexels-photo-1279107.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/1591174/pexels-photo-1591174.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    isNew: false,
    region: "india",
    createdAt: "2023-12-01T00:00:00Z",
    variants: {
      colors: [
        { name: "Black", value: "#000000" },
        { name: "Blue", value: "#0000FF" },
        { name: "Red", value: "#FF0000" },
      ],
    },
  },
  {
    id: "p8",
    name: "Handmade Ceramic Vase",
    description: "Artisanal ceramic vase with unique glazed finish. Each piece is one of a kind.",
    price: 1899,
    discount: 0,
    categoryId: "home-decor",
    categoryName: "Home Decor",
    stock: 35,
    images: [
      "https://images.pexels.com/photos/6045060/pexels-photo-6045060.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/6045383/pexels-photo-6045383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    isNew: true,
    region: "global",
    createdAt: "2024-01-15T00:00:00Z",
    variants: {
      colors: [
        { name: "White", value: "#FFFFFF" },
        { name: "Blue", value: "#0000FF" },
        { name: "Terracotta", value: "#E2725B" },
      ],
    },
  },
  {
    id: "p9",
    name: "Reading Glasses Set",
    description: "Set of 3 reading glasses in different strengths. Includes protective cases.",
    price: 1699,
    discount: 15,
    categoryId: "eyewear",
    categoryName: "Eyewear",
    stock: 65,
    images: [
      "https://images.pexels.com/photos/2811088/pexels-photo-2811088.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/1307217/pexels-photo-1307217.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    region: "india",
    createdAt: "2023-10-20T00:00:00Z",
    variants: {
      colors: [
        { name: "Black", value: "#000000" },
        { name: "Tortoise", value: "#8B4513" },
      ],
    },
  },
  {
    id: "p10",
    name: "Silk Scarf",
    description: "Luxurious pure silk scarf with hand-printed design. Perfect accessory for any season.",
    price: 1299,
    discount: 0,
    categoryId: "accessories",
    categoryName: "Accessories",
    stock: 110,
    images: [
      "https://images.pexels.com/photos/6044266/pexels-photo-6044266.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/11550162/pexels-photo-11550162.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    isBestseller: false,
    region: "global",
    createdAt: "2023-09-05T00:00:00Z",
    variants: {
      colors: [
        { name: "Blue Floral", value: "#0000FF" },
        { name: "Red Abstract", value: "#FF0000" },
      ],
    },
  },
  {
    id: "p11",
    name: "Smartphone Gimbal Stabilizer",
    description: "3-axis smartphone stabilizer for smooth video recording. Includes tracking and zoom features.",
    price: 6499,
    discount: 10,
    categoryId: "electronics",
    categoryName: "Electronics",
    stock: 40,
    images: [
      "https://images.pexels.com/photos/1552617/pexels-photo-1552617.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/633870/pexels-photo-633870.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    isNew: true,
    region: "usa",
    createdAt: "2024-01-10T00:00:00Z",
  },
  {
    id: "p12",
    name: "Macrame Wall Hanging",
    description: "Handcrafted macrame wall decoration made from 100% cotton rope. Beautiful bohemian accent.",
    price: 899,
    discount: 0,
    categoryId: "home-decor",
    categoryName: "Home Decor",
    stock: 55,
    images: [
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
      "https://images.pexels.com/photos/5417674/pexels-photo-5417674.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750",
    ],
    region: "india",
    createdAt: "2023-11-01T00:00:00Z",
    variants: {
      colors: [
        { name: "Natural", value: "#F5F5DC" },
        { name: "White", value: "#FFFFFF" },
      ],
    },
  },
];